
package Interfaces;

import java.awt.Image;
import javax.swing.ImageIcon;

public class frmInternalMedicalHistory extends javax.swing.JInternalFrame {

    public frmInternalMedicalHistory() {
        initComponents();
        
        ImageIcon imageIcon = new ImageIcon("src/images/iconArrowR_rbg.png");
        Image image = imageIcon.getImage();
        Image imageScaled = image.getScaledInstance(25, 25,
                java.awt.Image.SCALE_SMOOTH);
        
        imageIcon = new ImageIcon(imageScaled);
        
        jButton1.setIcon(imageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lbName1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbAge = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        tfAge = new javax.swing.JTextField();
        rbFem = new javax.swing.JRadioButton();
        rbMale = new javax.swing.JRadioButton();
        lbName2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lbAge1 = new javax.swing.JLabel();
        lbAge2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        lbName3 = new javax.swing.JLabel();
        tfName1 = new javax.swing.JTextField();
        lbName4 = new javax.swing.JLabel();
        tfName2 = new javax.swing.JTextField();
        lbName5 = new javax.swing.JLabel();
        tfName3 = new javax.swing.JTextField();
        lbName6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        lbGender1 = new javax.swing.JLabel();
        rbFem1 = new javax.swing.JRadioButton();
        rbMale1 = new javax.swing.JRadioButton();
        tfName4 = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(222, 212, 210));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_rbg.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbName.setText("Full Name:");
        getContentPane().add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 81, 139, -1));

        tfName.setForeground(new java.awt.Color(153, 153, 153));
        tfName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfName.setText("Names ");
        tfName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });
        getContentPane().add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 79, 149, -1));

        lbName1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbName1.setText("Odontogram:");
        getContentPane().add(lbName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 36, 139, -1));

        jButton1.setBackground(new java.awt.Color(34, 111, 138));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconArrowR_rbg.png"))); // NOI18N
        jButton1.setText("Go to");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 27, 153, 34));

        lbAge.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbAge.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbAge.setText("Age:");
        getContentPane().add(lbAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 121, 70, -1));

        lbGender.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbGender.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbGender.setText("Gender:");
        getContentPane().add(lbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 117, 58, 38));

        tfAge.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(tfAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 119, 90, -1));

        rbFem.setBackground(new java.awt.Color(222, 212, 210));
        rbFem.setText("Female");
        rbFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemActionPerformed(evt);
            }
        });
        getContentPane().add(rbFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 117, 91, -1));

        rbMale.setBackground(new java.awt.Color(222, 212, 210));
        rbMale.setText("Male");
        getContentPane().add(rbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 117, 77, -1));

        lbName2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbName2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbName2.setText("Medical Consultation Motive:");
        getContentPane().add(lbName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 173, 499, -1));

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 202, 499, -1));

        lbAge1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbAge1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbAge1.setText("Habits:");
        getContentPane().add(lbAge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 318, 90, -1));

        lbAge2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbAge2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbAge2.setText("Allergies:");
        getContentPane().add(lbAge2, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 318, 90, -1));

        jCheckBox1.setBackground(new java.awt.Color(222, 212, 210));
        jCheckBox1.setText("Use floss");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 343, 170, -1));

        jCheckBox2.setBackground(new java.awt.Color(222, 212, 210));
        jCheckBox2.setText("Use mouthwash");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 368, 170, -1));

        jCheckBox3.setBackground(new java.awt.Color(222, 212, 210));
        jCheckBox3.setText("Use fluoride toothpaste");
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 393, 170, -1));

        jCheckBox4.setBackground(new java.awt.Color(222, 212, 210));
        jCheckBox4.setText("Regular checkups");
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 418, 170, -1));

        jCheckBox5.setBackground(new java.awt.Color(222, 212, 210));
        jCheckBox5.setText("Latex Allergy");
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 343, 170, -1));

        jCheckBox6.setBackground(new java.awt.Color(222, 212, 210));
        jCheckBox6.setText("Anesthetic Allergies");
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 368, 170, -1));

        jCheckBox7.setBackground(new java.awt.Color(222, 212, 210));
        jCheckBox7.setText("Adhesive Allergies");
        getContentPane().add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 393, 170, -1));

        jCheckBox8.setBackground(new java.awt.Color(222, 212, 210));
        jCheckBox8.setText("Toothpaste ingredients");
        getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 418, 170, -1));

        lbName3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbName3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbName3.setText("Bucal Higiene:");
        getContentPane().add(lbName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 463, 165, -1));

        tfName1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tfName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfName1ActionPerformed(evt);
            }
        });
        getContentPane().add(tfName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 461, 292, -1));

        lbName4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbName4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbName4.setText("Present Illness:");
        getContentPane().add(lbName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 496, 165, -1));

        tfName2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tfName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfName2ActionPerformed(evt);
            }
        });
        getContentPane().add(tfName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 494, 292, -1));

        lbName5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbName5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbName5.setText("Blod Type:");
        getContentPane().add(lbName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 529, 134, -1));

        tfName3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tfName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfName3ActionPerformed(evt);
            }
        });
        getContentPane().add(tfName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 527, 292, -1));

        lbName6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbName6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbName6.setText("Medical Observations:");
        getContentPane().add(lbName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 560, 495, -1));

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 583, 495, -1));

        lbGender1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbGender1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbGender1.setText("Pregnant:");
        getContentPane().add(lbGender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 694, 243, 48));

        rbFem1.setBackground(new java.awt.Color(222, 212, 210));
        rbFem1.setText("Yes");
        rbFem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFem1ActionPerformed(evt);
            }
        });
        getContentPane().add(rbFem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 706, 91, -1));

        rbMale1.setBackground(new java.awt.Color(222, 212, 210));
        rbMale1.setText("No");
        getContentPane().add(rbMale1, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 706, 77, -1));

        tfName4.setForeground(new java.awt.Color(153, 153, 153));
        tfName4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfName4.setText("Last Names ");
        tfName4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tfName4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfName4ActionPerformed(evt);
            }
        });
        getContentPane().add(tfName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 79, 169, -1));

        btAdd.setBackground(new java.awt.Color(34, 111, 138));
        btAdd.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btAdd.setForeground(new java.awt.Color(255, 255, 255));
        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        getContentPane().add(btAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 750, 136, -1));

        btEdit.setBackground(new java.awt.Color(34, 111, 138));
        btEdit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btEdit.setForeground(new java.awt.Color(255, 255, 255));
        btEdit.setText("Edit");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });
        getContentPane().add(btEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 750, 136, -1));

        btDelete.setBackground(new java.awt.Color(34, 111, 138));
        btDelete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btDelete.setForeground(new java.awt.Color(255, 255, 255));
        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 750, 136, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void rbFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFemActionPerformed

    private void tfName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfName1ActionPerformed

    private void tfName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfName2ActionPerformed

    private void tfName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfName3ActionPerformed

    private void rbFem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFem1ActionPerformed

    private void tfName4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfName4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfName4ActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed

    }//GEN-LAST:event_btAddActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEditActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lbAge;
    private javax.swing.JLabel lbAge1;
    private javax.swing.JLabel lbAge2;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbGender1;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbName1;
    private javax.swing.JLabel lbName2;
    private javax.swing.JLabel lbName3;
    private javax.swing.JLabel lbName4;
    private javax.swing.JLabel lbName5;
    private javax.swing.JLabel lbName6;
    private javax.swing.JRadioButton rbFem;
    private javax.swing.JRadioButton rbFem1;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JRadioButton rbMale1;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfName1;
    private javax.swing.JTextField tfName2;
    private javax.swing.JTextField tfName3;
    private javax.swing.JTextField tfName4;
    // End of variables declaration//GEN-END:variables
}
