/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

/**
 *
 * @author vicky
 */
public class frmInternalAddPatient extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmInternalAddPatient
     */
    public frmInternalAddPatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        lbUserIcon = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        btChangePassword = new javax.swing.JButton();
        btLogIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jInternalFrame1.setBackground(new java.awt.Color(222, 212, 210));
        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setTitle("Log In");
        jInternalFrame1.setToolTipText("");

        lbUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconUser_rbg.png"))); // NOI18N
        lbUserIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbUser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbUser.setText("User:");

        lbPassword.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPassword.setText("Password: ");

        tfUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tfUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfUserKeyTyped(evt);
            }
        });

        pfPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pfPasswordKeyTyped(evt);
            }
        });

        btChangePassword.setBackground(new java.awt.Color(34, 111, 138));
        btChangePassword.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        btChangePassword.setText("Forgot Password?");

        btLogIn.setBackground(new java.awt.Color(34, 111, 138));
        btLogIn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btLogIn.setForeground(new java.awt.Color(255, 255, 255));
        btLogIn.setText("Log in");
        btLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(66, 66, 66)
                .addComponent(btLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfUser, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(pfPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUser)
                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPassword)
                    .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btChangePassword)
                    .addComponent(btLogIn))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(222, 212, 210));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel1)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(158, 158, 158))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUserKeyTyped
        int size = 15;
        char charac = evt.getKeyChar();
        if(charac == KeyEvent.VK_ENTER)
        authUser();
        else {
            if(!Character.isLetter(charac) && charac != KeyEvent.VK_BACK_SPACE) {
                getToolkit().beep();
                evt.consume();
                JOptionPane.showInternalMessageDialog(this, "Solo capturar letras", "¡ADVERTENCIA!", JOptionPane.WARNING_MESSAGE);
            }

            if(pfPassword.getText().length() >= size && charac != KeyEvent.VK_ENTER) {
                getToolkit().beep();
                evt.consume();
                JOptionPane.showInternalMessageDialog(this, "Máximo 5 dígitos.", "¡ADVERTENCIA!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_tfUserKeyTyped

    private void pfPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfPasswordKeyTyped
        int size = 5;
        char charac = evt.getKeyChar();
        if(charac == KeyEvent.VK_ENTER)
        authUser();
        else {
            if(!Character.isDigit(charac) && charac != KeyEvent.VK_BACK_SPACE) {
                getToolkit().beep();
                evt.consume();
                JOptionPane.showInternalMessageDialog(this, "Solo capturar números", "¡ADVERTENCIA!", JOptionPane.WARNING_MESSAGE);
            }

            if(pfPassword.getText().length() >= size && charac != KeyEvent.VK_ENTER) {
                getToolkit().beep();
                evt.consume();
                JOptionPane.showInternalMessageDialog(this, "Máximo 5 dígitos.", "¡ADVERTENCIA!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_pfPasswordKeyTyped

    private void btLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogInActionPerformed
        authUser();
    }//GEN-LAST:event_btLogInActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChangePassword;
    private javax.swing.JButton btLogIn;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbUser;
    private javax.swing.JLabel lbUserIcon;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
