package Interfaces;

import dentalware.Assistant;
import dentalware.Doctor;
import dentalware.User;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class frmInternalLogIn extends javax.swing.JInternalFrame {
    private frmGeneralWelcome generalMenu;
    private Assistant assis;
    private Doctor doctors;
    private User admin;
    
    public frmInternalLogIn(frmGeneralWelcome generalMenu, Assistant assis, Doctor doctors, User admin) {
        initComponents();
        this.generalMenu = generalMenu;
        
        this.assis = assis;
        this.doctors = doctors;
        this.admin = admin;
        
        /**String name, int age, char sex, String address, 
            String telephone, String user, String password, int type*/
        /*aUsuarios[0] = new User("Francisco Robles", 34, 'M', "Paseos del sol #24", 
                "33 1625 8596", "admin", "98765", 0);
        aUsuarios[1] = new User("Daniela Sandoval", 30, 'F', "Av. Rincones de soledad", 
                "33 4859 8456", "doctor", "45654", 1);
        aUsuarios[2] = new User("Miranda Ortega", 25, 'F', "Osa mayor 8957", 
                "33 1523 4865", "assis", "1234", 2);*/
        
        Color colorbg = new Color(222, 212, 210);
        getContentPane().setBackground(colorbg);
        
        // user icon:
        ImageIcon imageIcon = new ImageIcon("src/images/iconUser_rbg.png");
        Image image = imageIcon.getImage();
        Image imageScaled = image.getScaledInstance(140, 150,
                java.awt.Image.SCALE_SMOOTH);
        
        imageIcon = new ImageIcon(imageScaled);
        
        lbUserIcon.setIcon(imageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUserIcon = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        btChangePassword = new javax.swing.JButton();
        btLogIn = new javax.swing.JButton();

        setBackground(new java.awt.Color(222, 212, 210));
        setClosable(true);
        setIconifiable(true);
        setTitle("Log In");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_rbg.png"))); // NOI18N

        lbUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconUser_rbg.png"))); // NOI18N
        lbUserIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbUser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbUser.setText("User:");

        lbPassword.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPassword.setText("Password: ");

        tfUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tfUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfUserKeyTyped(evt);
            }
        });

        pfPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pfPasswordKeyTyped(evt);
            }
        });

        btChangePassword.setBackground(new java.awt.Color(34, 111, 138));
        btChangePassword.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        btChangePassword.setText("Forgot Password?");

        btLogIn.setBackground(new java.awt.Color(34, 111, 138));
        btLogIn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btLogIn.setForeground(new java.awt.Color(255, 255, 255));
        btLogIn.setText("Log in");
        btLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(66, 66, 66)
                .addComponent(btLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfUser, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(pfPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUser)
                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPassword)
                    .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btChangePassword)
                    .addComponent(btLogIn))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean authUser() {
        // obtener textos de usuario y contraseña
        String usr = tfUser.getText();
        String ctr = pfPassword.getText();
        boolean valid = false;
        // System.out.println("Sí inicio we");
        
        if(!usr.isEmpty() && !ctr.isEmpty()) {
            // System.out.println("Sí comienzo a buscar we");
            // bandera para determinar validez de usuario
            // validar el acceso o no
            while(assis != null || doctors != null || admin != null) {
                if(admin.getUser().equals(usr) && admin.getPassword().equals(ctr)) {
                    frmWelcomeAdmin frmAdmin = new frmWelcomeAdmin(generalMenu, assis, doctors);
                    frmAdmin.setVisible(true);
                    generalMenu.setVisible(false);
                    valid = true;
                    break;
                }
                if(assis.getUser().equals(usr) && assis.getPassword().equals(ctr)) {
                    /*frmWelcomeAssis frmAssis = new frmWelcomeAssis(generalMenu, assis, doctors);
                    frmAssis.setVisible(true);
                    generalMenu.setVisible(false);
                    valid = true;
                    break;*/
                }
                if(doctors.getUser().equals(usr) && doctors.getPassword().equals(ctr)) {
                    /*frmWelcomeDoctor frmDoct = new frmWelcomeDoctor(generalMenu, assis, doctors);
                    frmDoct.setVisible(true);
                    generalMenu.setVisible(false);
                    valid = true;
                    break;*/
                }
                assis = assis.getNext();
                doctors = doctors.getNext();
            }
            tfUser.setText("");
            pfPassword.setText("");
            tfUser.requestFocus();
            if (!valid)
                // System.out.println("Sí llegué we");
                JOptionPane.showInternalMessageDialog(this, "El usuario o la contraseña\ningresados son incorrectos", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
        } else
            JOptionPane.showInternalMessageDialog(this, "Asegurese de llenar\ntodos los campos", "¡ERROR!", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    
    private void btLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogInActionPerformed
        authUser();
    }//GEN-LAST:event_btLogInActionPerformed

    private void pfPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfPasswordKeyTyped
        int size = 5;
        char charac = evt.getKeyChar();
        if(charac == KeyEvent.VK_ENTER)
            authUser();
        else {
            if(!Character.isDigit(charac) && charac != KeyEvent.VK_BACK_SPACE) {
                getToolkit().beep();
                evt.consume();
                JOptionPane.showInternalMessageDialog(this, "Solo capturar números", "¡ADVERTENCIA!", JOptionPane.WARNING_MESSAGE);
            }
            
            if(pfPassword.getText().length() >= size && charac != KeyEvent.VK_ENTER) {
                getToolkit().beep();
                evt.consume();
                JOptionPane.showInternalMessageDialog(this, "Máximo 5 dígitos.", "¡ADVERTENCIA!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_pfPasswordKeyTyped

    private void tfUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUserKeyTyped
        int size = 15;
        char charac = evt.getKeyChar();
        if(charac == KeyEvent.VK_ENTER)
            authUser();
        else {
            if(!Character.isLetter(charac) && charac != KeyEvent.VK_BACK_SPACE) {
                getToolkit().beep();
                evt.consume();
                JOptionPane.showInternalMessageDialog(this, "Solo capturar letras", "¡ADVERTENCIA!", JOptionPane.WARNING_MESSAGE);
            }
            
            if(pfPassword.getText().length() >= size && charac != KeyEvent.VK_ENTER) {
                getToolkit().beep();
                evt.consume();
                JOptionPane.showInternalMessageDialog(this, "Máximo 5 dígitos.", "¡ADVERTENCIA!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_tfUserKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChangePassword;
    private javax.swing.JButton btLogIn;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbUser;
    private javax.swing.JLabel lbUserIcon;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
