
package Interfaces;

public class frmInternalPatientInfo extends javax.swing.JInternalFrame {

    public frmInternalPatientInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUserIcon = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbFileNumber = new javax.swing.JLabel();
        btnPayment = new javax.swing.JButton();
        btnQuoting = new javax.swing.JButton();
        btnMedical = new javax.swing.JButton();

        setBackground(new java.awt.Color(222, 212, 210));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lbUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconUser_rbg.png"))); // NOI18N
        lbUserIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbName.setText("Name");

        lbFileNumber.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbFileNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFileNumber.setText("File #000000");

        btnPayment.setBackground(new java.awt.Color(34, 111, 138));
        btnPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnPayment.setText("Payment History");

        btnQuoting.setBackground(new java.awt.Color(34, 111, 138));
        btnQuoting.setForeground(new java.awt.Color(255, 255, 255));
        btnQuoting.setText("Quoting");

        btnMedical.setBackground(new java.awt.Color(34, 111, 138));
        btnMedical.setForeground(new java.awt.Color(255, 255, 255));
        btnMedical.setText("Medical History");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(lbFileNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPayment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuoting)
                .addGap(59, 59, 59)
                .addComponent(btnMedical)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 164, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbFileNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lbName)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPayment)
                    .addComponent(btnMedical)
                    .addComponent(btnQuoting))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMedical;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnQuoting;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbFileNumber;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbUserIcon;
    // End of variables declaration//GEN-END:variables
}
