
package Interfaces;

public class frmInternalOdontogram extends javax.swing.JInternalFrame {

    public frmInternalOdontogram() {
        initComponents();    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb11 = new javax.swing.JCheckBox();
        cb12 = new javax.swing.JCheckBox();
        cb13 = new javax.swing.JCheckBox();
        cb14 = new javax.swing.JCheckBox();
        cb15 = new javax.swing.JCheckBox();
        cb16 = new javax.swing.JCheckBox();
        cb17 = new javax.swing.JCheckBox();
        cb18 = new javax.swing.JCheckBox();
        cb21 = new javax.swing.JCheckBox();
        cb22 = new javax.swing.JCheckBox();
        cb23 = new javax.swing.JCheckBox();
        cb24 = new javax.swing.JCheckBox();
        cb25 = new javax.swing.JCheckBox();
        cb26 = new javax.swing.JCheckBox();
        cb27 = new javax.swing.JCheckBox();
        cb28 = new javax.swing.JCheckBox();
        cb31 = new javax.swing.JCheckBox();
        cb32 = new javax.swing.JCheckBox();
        cb33 = new javax.swing.JCheckBox();
        cb34 = new javax.swing.JCheckBox();
        cb35 = new javax.swing.JCheckBox();
        cb36 = new javax.swing.JCheckBox();
        cb37 = new javax.swing.JCheckBox();
        cb38 = new javax.swing.JCheckBox();
        cb41 = new javax.swing.JCheckBox();
        cb42 = new javax.swing.JCheckBox();
        cb43 = new javax.swing.JCheckBox();
        cb44 = new javax.swing.JCheckBox();
        cb45 = new javax.swing.JCheckBox();
        cb46 = new javax.swing.JCheckBox();
        cb47 = new javax.swing.JCheckBox();
        cb48 = new javax.swing.JCheckBox();
        pnlOdontogram = new Odontogram.pnlOdontogram();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMaximumSize(new java.awt.Dimension(450, 709));
        setMinimumSize(new java.awt.Dimension(450, 709));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb11.setBackground(new java.awt.Color(255, 255, 255));
        cb11.setHideActionText(true);
        cb11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 20, 20));

        cb12.setBackground(new java.awt.Color(255, 255, 255));
        cb12.setHideActionText(true);
        cb12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 20, 20));

        cb13.setBackground(new java.awt.Color(255, 255, 255));
        cb13.setHideActionText(true);
        cb13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 20, 20));

        cb14.setBackground(new java.awt.Color(255, 255, 255));
        cb14.setHideActionText(true);
        cb14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 20, 20));

        cb15.setBackground(new java.awt.Color(255, 255, 255));
        cb15.setHideActionText(true);
        cb15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 20, 20));

        cb16.setBackground(new java.awt.Color(255, 255, 255));
        cb16.setHideActionText(true);
        cb16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 20, 20));

        cb17.setBackground(new java.awt.Color(255, 255, 255));
        cb17.setHideActionText(true);
        cb17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 20, 20));

        cb18.setBackground(new java.awt.Color(255, 255, 255));
        cb18.setHideActionText(true);
        cb18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 20, 20));

        cb21.setBackground(new java.awt.Color(255, 255, 255));
        cb21.setHideActionText(true);
        cb21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 20, 20));

        cb22.setBackground(new java.awt.Color(255, 255, 255));
        cb22.setHideActionText(true);
        cb22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb22, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 20, 20));

        cb23.setBackground(new java.awt.Color(255, 255, 255));
        cb23.setHideActionText(true);
        cb23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 20, 20));

        cb24.setBackground(new java.awt.Color(255, 255, 255));
        cb24.setHideActionText(true);
        cb24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 20, 20));

        cb25.setBackground(new java.awt.Color(255, 255, 255));
        cb25.setHideActionText(true);
        cb25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 20, 20));

        cb26.setBackground(new java.awt.Color(255, 255, 255));
        cb26.setHideActionText(true);
        cb26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 20, 20));

        cb27.setBackground(new java.awt.Color(255, 255, 255));
        cb27.setHideActionText(true);
        cb27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb27, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 20, 20));

        cb28.setBackground(new java.awt.Color(255, 255, 255));
        cb28.setHideActionText(true);
        cb28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb28, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 20, 20));

        cb31.setBackground(new java.awt.Color(255, 255, 255));
        cb31.setHideActionText(true);
        cb31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb31, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, 20, 20));

        cb32.setBackground(new java.awt.Color(255, 255, 255));
        cb32.setHideActionText(true);
        cb32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb32, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, 20, 20));

        cb33.setBackground(new java.awt.Color(255, 255, 255));
        cb33.setHideActionText(true);
        cb33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb33, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, 20, 20));

        cb34.setBackground(new java.awt.Color(255, 255, 255));
        cb34.setHideActionText(true);
        cb34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb34, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 20, 20));

        cb35.setBackground(new java.awt.Color(255, 255, 255));
        cb35.setHideActionText(true);
        cb35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb35, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 20, 20));

        cb36.setBackground(new java.awt.Color(255, 255, 255));
        cb36.setHideActionText(true);
        cb36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb36, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 20, 20));

        cb37.setBackground(new java.awt.Color(255, 255, 255));
        cb37.setHideActionText(true);
        cb37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb37, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 20, 20));

        cb38.setBackground(new java.awt.Color(255, 255, 255));
        cb38.setHideActionText(true);
        cb38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb38, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 20, 20));

        cb41.setBackground(new java.awt.Color(255, 255, 255));
        cb41.setHideActionText(true);
        cb41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb41, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 20, 20));

        cb42.setBackground(new java.awt.Color(255, 255, 255));
        cb42.setHideActionText(true);
        cb42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb42.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb42, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 610, 20, 20));

        cb43.setBackground(new java.awt.Color(255, 255, 255));
        cb43.setHideActionText(true);
        cb43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb43.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb43, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 20, 20));

        cb44.setBackground(new java.awt.Color(255, 255, 255));
        cb44.setHideActionText(true);
        cb44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb44.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb44, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 20, 20));

        cb45.setBackground(new java.awt.Color(255, 255, 255));
        cb45.setHideActionText(true);
        cb45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb45.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb45, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 20, 20));

        cb46.setBackground(new java.awt.Color(255, 255, 255));
        cb46.setHideActionText(true);
        cb46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb46.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb46, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 20, 20));

        cb47.setBackground(new java.awt.Color(255, 255, 255));
        cb47.setHideActionText(true);
        cb47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb47.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb47, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 20, 20));

        cb48.setBackground(new java.awt.Color(255, 255, 255));
        cb48.setHideActionText(true);
        cb48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cb48.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(cb48, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 20, 20));
        getContentPane().add(pnlOdontogram, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb11;
    private javax.swing.JCheckBox cb12;
    private javax.swing.JCheckBox cb13;
    private javax.swing.JCheckBox cb14;
    private javax.swing.JCheckBox cb15;
    private javax.swing.JCheckBox cb16;
    private javax.swing.JCheckBox cb17;
    private javax.swing.JCheckBox cb18;
    private javax.swing.JCheckBox cb21;
    private javax.swing.JCheckBox cb22;
    private javax.swing.JCheckBox cb23;
    private javax.swing.JCheckBox cb24;
    private javax.swing.JCheckBox cb25;
    private javax.swing.JCheckBox cb26;
    private javax.swing.JCheckBox cb27;
    private javax.swing.JCheckBox cb28;
    private javax.swing.JCheckBox cb31;
    private javax.swing.JCheckBox cb32;
    private javax.swing.JCheckBox cb33;
    private javax.swing.JCheckBox cb34;
    private javax.swing.JCheckBox cb35;
    private javax.swing.JCheckBox cb36;
    private javax.swing.JCheckBox cb37;
    private javax.swing.JCheckBox cb38;
    private javax.swing.JCheckBox cb41;
    private javax.swing.JCheckBox cb42;
    private javax.swing.JCheckBox cb43;
    private javax.swing.JCheckBox cb44;
    private javax.swing.JCheckBox cb45;
    private javax.swing.JCheckBox cb46;
    private javax.swing.JCheckBox cb47;
    private javax.swing.JCheckBox cb48;
    private Odontogram.pnlOdontogram pnlOdontogram;
    // End of variables declaration//GEN-END:variables
}
