
package Interfaces;

public class frmInternalOdontogram extends javax.swing.JInternalFrame {

    public frmInternalOdontogram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rb11 = new javax.swing.JRadioButton();
        rb12 = new javax.swing.JRadioButton();
        rb13 = new javax.swing.JRadioButton();
        rb14 = new javax.swing.JRadioButton();
        rb15 = new javax.swing.JRadioButton();
        rb16 = new javax.swing.JRadioButton();
        rb17 = new javax.swing.JRadioButton();
        rb18 = new javax.swing.JRadioButton();
        rb21 = new javax.swing.JRadioButton();
        rb22 = new javax.swing.JRadioButton();
        rb23 = new javax.swing.JRadioButton();
        rb24 = new javax.swing.JRadioButton();
        rb25 = new javax.swing.JRadioButton();
        rb26 = new javax.swing.JRadioButton();
        rb27 = new javax.swing.JRadioButton();
        rb28 = new javax.swing.JRadioButton();
        rb31 = new javax.swing.JRadioButton();
        rb32 = new javax.swing.JRadioButton();
        rb33 = new javax.swing.JRadioButton();
        rb34 = new javax.swing.JRadioButton();
        rb35 = new javax.swing.JRadioButton();
        rb36 = new javax.swing.JRadioButton();
        rb37 = new javax.swing.JRadioButton();
        rb38 = new javax.swing.JRadioButton();
        rb41 = new javax.swing.JRadioButton();
        rb42 = new javax.swing.JRadioButton();
        rb43 = new javax.swing.JRadioButton();
        rb44 = new javax.swing.JRadioButton();
        rb45 = new javax.swing.JRadioButton();
        rb46 = new javax.swing.JRadioButton();
        rb47 = new javax.swing.JRadioButton();
        rb49 = new javax.swing.JRadioButton();
        pnlOdontogram = new Odontogram.pnlOdontogram();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rb11.setBackground(new java.awt.Color(255, 255, 255));
        rb11.setAlignmentY(0.0F);
        rb11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb11.setIconTextGap(0);
        rb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb11ActionPerformed(evt);
            }
        });
        getContentPane().add(rb11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 20, 20));

        rb12.setBackground(new java.awt.Color(255, 255, 255));
        rb12.setAlignmentY(0.0F);
        rb12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb12.setIconTextGap(0);
        rb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb12ActionPerformed(evt);
            }
        });
        getContentPane().add(rb12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 20, 20));

        rb13.setBackground(new java.awt.Color(255, 255, 255));
        rb13.setAlignmentY(0.0F);
        rb13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb13.setIconTextGap(0);
        rb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb13ActionPerformed(evt);
            }
        });
        getContentPane().add(rb13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 20, 20));

        rb14.setBackground(new java.awt.Color(255, 255, 255));
        rb14.setAlignmentY(0.0F);
        rb14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb14.setIconTextGap(0);
        rb14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb14ActionPerformed(evt);
            }
        });
        getContentPane().add(rb14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 20, 20));

        rb15.setBackground(new java.awt.Color(255, 255, 255));
        rb15.setAlignmentY(0.0F);
        rb15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb15.setIconTextGap(0);
        rb15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb15ActionPerformed(evt);
            }
        });
        getContentPane().add(rb15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 20, 20));

        rb16.setBackground(new java.awt.Color(255, 255, 255));
        rb16.setAlignmentY(0.0F);
        rb16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb16.setIconTextGap(0);
        rb16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb16ActionPerformed(evt);
            }
        });
        getContentPane().add(rb16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 20, 20));

        rb17.setBackground(new java.awt.Color(255, 255, 255));
        rb17.setAlignmentY(0.0F);
        rb17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb17.setIconTextGap(0);
        rb17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb17ActionPerformed(evt);
            }
        });
        getContentPane().add(rb17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 20, 20));

        rb18.setBackground(new java.awt.Color(255, 255, 255));
        rb18.setAlignmentY(0.0F);
        rb18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb18.setIconTextGap(0);
        rb18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb18ActionPerformed(evt);
            }
        });
        getContentPane().add(rb18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 20, 20));

        rb21.setBackground(new java.awt.Color(255, 255, 255));
        rb21.setAlignmentY(0.0F);
        rb21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb21.setIconTextGap(0);
        rb21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb21ActionPerformed(evt);
            }
        });
        getContentPane().add(rb21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 20, 20));

        rb22.setBackground(new java.awt.Color(255, 255, 255));
        rb22.setAlignmentY(0.0F);
        rb22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb22.setIconTextGap(0);
        rb22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb22ActionPerformed(evt);
            }
        });
        getContentPane().add(rb22, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 20, 20));

        rb23.setBackground(new java.awt.Color(255, 255, 255));
        rb23.setAlignmentY(0.0F);
        rb23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb23.setIconTextGap(0);
        rb23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb23ActionPerformed(evt);
            }
        });
        getContentPane().add(rb23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 20, 20));

        rb24.setBackground(new java.awt.Color(255, 255, 255));
        rb24.setAlignmentY(0.0F);
        rb24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb24.setIconTextGap(0);
        rb24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb24ActionPerformed(evt);
            }
        });
        getContentPane().add(rb24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 20, 20));

        rb25.setBackground(new java.awt.Color(255, 255, 255));
        rb25.setAlignmentY(0.0F);
        rb25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb25.setIconTextGap(0);
        rb25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb25ActionPerformed(evt);
            }
        });
        getContentPane().add(rb25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 20, 20));

        rb26.setBackground(new java.awt.Color(255, 255, 255));
        rb26.setAlignmentY(0.0F);
        rb26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb26.setIconTextGap(0);
        rb26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb26ActionPerformed(evt);
            }
        });
        getContentPane().add(rb26, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 20, 20));

        rb27.setBackground(new java.awt.Color(255, 255, 255));
        rb27.setAlignmentY(0.0F);
        rb27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb27.setIconTextGap(0);
        rb27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb27ActionPerformed(evt);
            }
        });
        getContentPane().add(rb27, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 20, 20));

        rb28.setBackground(new java.awt.Color(255, 255, 255));
        rb28.setAlignmentY(0.0F);
        rb28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb28.setIconTextGap(0);
        rb28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb28ActionPerformed(evt);
            }
        });
        getContentPane().add(rb28, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 20, 20));

        rb31.setBackground(new java.awt.Color(255, 255, 255));
        rb31.setAlignmentY(0.0F);
        rb31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb31.setIconTextGap(0);
        rb31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb31ActionPerformed(evt);
            }
        });
        getContentPane().add(rb31, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, 20, 20));

        rb32.setBackground(new java.awt.Color(255, 255, 255));
        rb32.setAlignmentY(0.0F);
        rb32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb32.setIconTextGap(0);
        rb32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb32ActionPerformed(evt);
            }
        });
        getContentPane().add(rb32, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, 20, 20));

        rb33.setBackground(new java.awt.Color(255, 255, 255));
        rb33.setAlignmentY(0.0F);
        rb33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb33.setIconTextGap(0);
        rb33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb33ActionPerformed(evt);
            }
        });
        getContentPane().add(rb33, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 20, 20));

        rb34.setBackground(new java.awt.Color(255, 255, 255));
        rb34.setAlignmentY(0.0F);
        rb34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb34.setIconTextGap(0);
        rb34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb34ActionPerformed(evt);
            }
        });
        getContentPane().add(rb34, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 20, 20));

        rb35.setBackground(new java.awt.Color(255, 255, 255));
        rb35.setAlignmentY(0.0F);
        rb35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb35.setIconTextGap(0);
        rb35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb35ActionPerformed(evt);
            }
        });
        getContentPane().add(rb35, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 20, 20));

        rb36.setBackground(new java.awt.Color(255, 255, 255));
        rb36.setAlignmentY(0.0F);
        rb36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb36.setIconTextGap(0);
        rb36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb36ActionPerformed(evt);
            }
        });
        getContentPane().add(rb36, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 20, 20));

        rb37.setBackground(new java.awt.Color(255, 255, 255));
        rb37.setAlignmentY(0.0F);
        rb37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb37.setIconTextGap(0);
        rb37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb37ActionPerformed(evt);
            }
        });
        getContentPane().add(rb37, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 20, 20));

        rb38.setBackground(new java.awt.Color(255, 255, 255));
        rb38.setAlignmentY(0.0F);
        rb38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb38.setIconTextGap(0);
        rb38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb38ActionPerformed(evt);
            }
        });
        getContentPane().add(rb38, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 20, 20));

        rb41.setBackground(new java.awt.Color(255, 255, 255));
        rb41.setAlignmentY(0.0F);
        rb41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb41.setIconTextGap(0);
        rb41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb41ActionPerformed(evt);
            }
        });
        getContentPane().add(rb41, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, 20, 20));

        rb42.setBackground(new java.awt.Color(255, 255, 255));
        rb42.setAlignmentY(0.0F);
        rb42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb42.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb42.setIconTextGap(0);
        rb42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb42ActionPerformed(evt);
            }
        });
        getContentPane().add(rb42, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, 20, 20));

        rb43.setBackground(new java.awt.Color(255, 255, 255));
        rb43.setAlignmentY(0.0F);
        rb43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb43.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb43.setIconTextGap(0);
        rb43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb43ActionPerformed(evt);
            }
        });
        getContentPane().add(rb43, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 20, 20));

        rb44.setBackground(new java.awt.Color(255, 255, 255));
        rb44.setAlignmentY(0.0F);
        rb44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb44.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb44.setIconTextGap(0);
        rb44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb44ActionPerformed(evt);
            }
        });
        getContentPane().add(rb44, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 20, 20));

        rb45.setBackground(new java.awt.Color(255, 255, 255));
        rb45.setAlignmentY(0.0F);
        rb45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb45.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb45.setIconTextGap(0);
        rb45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb45ActionPerformed(evt);
            }
        });
        getContentPane().add(rb45, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 20, 20));

        rb46.setBackground(new java.awt.Color(255, 255, 255));
        rb46.setAlignmentY(0.0F);
        rb46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb46.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb46.setIconTextGap(0);
        rb46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb46ActionPerformed(evt);
            }
        });
        getContentPane().add(rb46, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 20, 20));

        rb47.setBackground(new java.awt.Color(255, 255, 255));
        rb47.setAlignmentY(0.0F);
        rb47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb47.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb47.setIconTextGap(0);
        rb47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb47ActionPerformed(evt);
            }
        });
        getContentPane().add(rb47, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 20, 20));

        rb49.setBackground(new java.awt.Color(255, 255, 255));
        rb49.setAlignmentY(0.0F);
        rb49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rb49.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rb49.setIconTextGap(0);
        rb49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb49ActionPerformed(evt);
            }
        });
        getContentPane().add(rb49, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 20, 20));
        getContentPane().add(pnlOdontogram, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb11ActionPerformed

    private void rb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb12ActionPerformed

    private void rb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb13ActionPerformed

    private void rb14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb14ActionPerformed

    private void rb15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb15ActionPerformed

    private void rb16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb16ActionPerformed

    private void rb17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb17ActionPerformed

    private void rb18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb18ActionPerformed

    private void rb21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb21ActionPerformed

    private void rb22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb22ActionPerformed

    private void rb23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb23ActionPerformed

    private void rb24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb24ActionPerformed

    private void rb25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb25ActionPerformed

    private void rb26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb26ActionPerformed

    private void rb27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb27ActionPerformed

    private void rb28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb28ActionPerformed

    private void rb31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb31ActionPerformed

    private void rb32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb32ActionPerformed

    private void rb33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb33ActionPerformed

    private void rb34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb34ActionPerformed

    private void rb35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb35ActionPerformed

    private void rb36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb36ActionPerformed

    private void rb37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb37ActionPerformed

    private void rb38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb38ActionPerformed

    private void rb41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb41ActionPerformed

    private void rb42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb42ActionPerformed

    private void rb43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb43ActionPerformed

    private void rb44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb44ActionPerformed

    private void rb45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb45ActionPerformed

    private void rb46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb46ActionPerformed

    private void rb47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb47ActionPerformed

    private void rb49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb49ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Odontogram.pnlOdontogram pnlOdontogram;
    private javax.swing.JRadioButton rb11;
    private javax.swing.JRadioButton rb12;
    private javax.swing.JRadioButton rb13;
    private javax.swing.JRadioButton rb14;
    private javax.swing.JRadioButton rb15;
    private javax.swing.JRadioButton rb16;
    private javax.swing.JRadioButton rb17;
    private javax.swing.JRadioButton rb18;
    private javax.swing.JRadioButton rb21;
    private javax.swing.JRadioButton rb22;
    private javax.swing.JRadioButton rb23;
    private javax.swing.JRadioButton rb24;
    private javax.swing.JRadioButton rb25;
    private javax.swing.JRadioButton rb26;
    private javax.swing.JRadioButton rb27;
    private javax.swing.JRadioButton rb28;
    private javax.swing.JRadioButton rb31;
    private javax.swing.JRadioButton rb32;
    private javax.swing.JRadioButton rb33;
    private javax.swing.JRadioButton rb34;
    private javax.swing.JRadioButton rb35;
    private javax.swing.JRadioButton rb36;
    private javax.swing.JRadioButton rb37;
    private javax.swing.JRadioButton rb38;
    private javax.swing.JRadioButton rb41;
    private javax.swing.JRadioButton rb42;
    private javax.swing.JRadioButton rb43;
    private javax.swing.JRadioButton rb44;
    private javax.swing.JRadioButton rb45;
    private javax.swing.JRadioButton rb46;
    private javax.swing.JRadioButton rb47;
    private javax.swing.JRadioButton rb49;
    // End of variables declaration//GEN-END:variables
}
