package Interfaces;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

public class frmWelcomeAdmin extends javax.swing.JFrame {

    public frmWelcomeAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon("src/images/bgDesktop.jpg");
        Image img = icon.getImage();
        desktopPane = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g) {
                g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            }
        };
        MenuBar = new javax.swing.JMenuBar();
        menuDoctors = new javax.swing.JMenu();
        mItemAddDoct = new javax.swing.JMenuItem();
        mItemShowDoct = new javax.swing.JMenuItem();
        menuAssistants = new javax.swing.JMenu();
        mItemAddAssis = new javax.swing.JMenuItem();
        mItemShowAssis = new javax.swing.JMenuItem();
        menuSupplies = new javax.swing.JMenu();
        mItemDelSup = new javax.swing.JMenuItem();
        mItemShowSup = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(222, 212, 210));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1318, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        MenuBar.setBackground(new java.awt.Color(222, 212, 210));

        menuDoctors.setText("Doctors");

        mItemAddDoct.setText("Add doctor");
        mItemAddDoct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAddDoctActionPerformed(evt);
            }
        });
        menuDoctors.add(mItemAddDoct);

        mItemShowDoct.setText("Show doctors");
        menuDoctors.add(mItemShowDoct);

        MenuBar.add(menuDoctors);

        menuAssistants.setText("Assistants");

        mItemAddAssis.setText("Add assitants");
        mItemAddAssis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAddAssisActionPerformed(evt);
            }
        });
        menuAssistants.add(mItemAddAssis);

        mItemShowAssis.setText("Show assistants");
        menuAssistants.add(mItemShowAssis);

        MenuBar.add(menuAssistants);

        menuSupplies.setText("Supplies");

        mItemDelSup.setText("Delete supply");
        mItemDelSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemDelSupActionPerformed(evt);
            }
        });
        menuSupplies.add(mItemDelSup);

        mItemShowSup.setText("Show supplies");
        menuSupplies.add(mItemShowSup);

        MenuBar.add(menuSupplies);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItemAddDoctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAddDoctActionPerformed
        frmInternalLogIn logIn = new frmInternalLogIn();
        desktopPane.add(logIn);
        logIn.show();
    }//GEN-LAST:event_mItemAddDoctActionPerformed

    private void mItemAddAssisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAddAssisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mItemAddAssisActionPerformed

    private void mItemDelSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemDelSupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mItemDelSupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmWelcomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmWelcomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmWelcomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmWelcomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmWelcomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem mItemAddAssis;
    private javax.swing.JMenuItem mItemAddDoct;
    private javax.swing.JMenuItem mItemDelSup;
    private javax.swing.JMenuItem mItemShowAssis;
    private javax.swing.JMenuItem mItemShowDoct;
    private javax.swing.JMenuItem mItemShowSup;
    private javax.swing.JMenu menuAssistants;
    private javax.swing.JMenu menuDoctors;
    private javax.swing.JMenu menuSupplies;
    // End of variables declaration//GEN-END:variables
}
