
package Agenda;

import java.awt.Color;
import java.awt.Component;
import java.util.Calendar;

public class pnlDate extends javax.swing.JPanel {

    private int month, year;
    
    public pnlDate(int month, int year) {
        initComponents();
        
        this.month = month;
        this.year = year;
        
        init();
        
        Color colorbg = new Color(222, 212, 210);
        
    }

    private void init() {
        mon.asTitle();
        tue.asTitle();
        wed.asTitle();
        thu.asTitle();
        fri.asTitle();
        sat.asTitle();
        sun.asTitle();
        
        setDate();
    }
    
    private void setDate() {
        Calendar calendar = Calendar.getInstance();
        
        calendar.set(Calendar.YEAR, year);
        calendar.set(Calendar.MONTH, month-1);
        calendar.set(Calendar.DATE, 1);
        
        int startDay = calendar.get(Calendar.DAY_OF_WEEK) - 1;
        
        calendar.add(Calendar.DATE, -startDay);
        
        for(Component com:getComponents()) {
            Cell cell = (Cell)com;
            if(!cell.isTitle()) {
                cell.setText(calendar.get(Calendar.DATE) + "");
                cell.setDate(calendar.getTime());
                cell.currentMonth(calendar.get(Calendar.MONTH) == month - 1);
                calendar.add(Calendar.DATE, 1);
                
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sun = new Agenda.Cell();
        mon = new Agenda.Cell();
        tue = new Agenda.Cell();
        wed = new Agenda.Cell();
        thu = new Agenda.Cell();
        fri = new Agenda.Cell();
        sat = new Agenda.Cell();
        cell8 = new Agenda.Cell();
        cell9 = new Agenda.Cell();
        cell10 = new Agenda.Cell();
        cell11 = new Agenda.Cell();
        cell12 = new Agenda.Cell();
        cell13 = new Agenda.Cell();
        cell14 = new Agenda.Cell();
        cell15 = new Agenda.Cell();
        cell16 = new Agenda.Cell();
        cell17 = new Agenda.Cell();
        cell18 = new Agenda.Cell();
        cell19 = new Agenda.Cell();
        cell20 = new Agenda.Cell();
        cell21 = new Agenda.Cell();
        cell22 = new Agenda.Cell();
        cell23 = new Agenda.Cell();
        cell24 = new Agenda.Cell();
        cell25 = new Agenda.Cell();
        cell26 = new Agenda.Cell();
        cell27 = new Agenda.Cell();
        cell28 = new Agenda.Cell();
        cell29 = new Agenda.Cell();
        cell30 = new Agenda.Cell();
        cell31 = new Agenda.Cell();
        cell32 = new Agenda.Cell();
        cell33 = new Agenda.Cell();
        cell34 = new Agenda.Cell();
        cell35 = new Agenda.Cell();
        cell36 = new Agenda.Cell();
        cell37 = new Agenda.Cell();
        cell38 = new Agenda.Cell();
        cell39 = new Agenda.Cell();
        cell40 = new Agenda.Cell();
        cell41 = new Agenda.Cell();
        cell42 = new Agenda.Cell();
        cell43 = new Agenda.Cell();
        cell44 = new Agenda.Cell();
        cell45 = new Agenda.Cell();
        cell46 = new Agenda.Cell();
        cell47 = new Agenda.Cell();
        cell48 = new Agenda.Cell();
        cell49 = new Agenda.Cell();

        setLayout(new java.awt.GridLayout(7, 7));

        sun.setBackground(new java.awt.Color(222, 212, 210));
        sun.setForeground(new java.awt.Color(118, 194, 164));
        sun.setText("Sun");
        sun.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        add(sun);

        mon.setBackground(new java.awt.Color(222, 212, 210));
        mon.setForeground(new java.awt.Color(118, 194, 164));
        mon.setText("Mon");
        mon.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        add(mon);

        tue.setBackground(new java.awt.Color(222, 212, 210));
        tue.setForeground(new java.awt.Color(118, 194, 164));
        tue.setText("Tue");
        tue.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        add(tue);

        wed.setBackground(new java.awt.Color(222, 212, 210));
        wed.setForeground(new java.awt.Color(118, 194, 164));
        wed.setText("Wed");
        wed.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        add(wed);

        thu.setBackground(new java.awt.Color(222, 212, 210));
        thu.setForeground(new java.awt.Color(118, 194, 164));
        thu.setText("Thu");
        thu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        add(thu);

        fri.setBackground(new java.awt.Color(222, 212, 210));
        fri.setForeground(new java.awt.Color(118, 194, 164));
        fri.setText("Fri");
        fri.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        add(fri);

        sat.setBackground(new java.awt.Color(222, 212, 210));
        sat.setForeground(new java.awt.Color(118, 194, 164));
        sat.setText("Sat");
        sat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        add(sat);

        cell8.setBackground(new java.awt.Color(222, 212, 210));
        add(cell8);

        cell9.setBackground(new java.awt.Color(222, 212, 210));
        add(cell9);

        cell10.setBackground(new java.awt.Color(222, 212, 210));
        add(cell10);

        cell11.setBackground(new java.awt.Color(222, 212, 210));
        add(cell11);

        cell12.setBackground(new java.awt.Color(222, 212, 210));
        add(cell12);

        cell13.setBackground(new java.awt.Color(222, 212, 210));
        add(cell13);

        cell14.setBackground(new java.awt.Color(222, 212, 210));
        add(cell14);

        cell15.setBackground(new java.awt.Color(222, 212, 210));
        add(cell15);

        cell16.setBackground(new java.awt.Color(222, 212, 210));
        add(cell16);

        cell17.setBackground(new java.awt.Color(222, 212, 210));
        add(cell17);

        cell18.setBackground(new java.awt.Color(222, 212, 210));
        add(cell18);

        cell19.setBackground(new java.awt.Color(222, 212, 210));
        add(cell19);

        cell20.setBackground(new java.awt.Color(222, 212, 210));
        add(cell20);

        cell21.setBackground(new java.awt.Color(222, 212, 210));
        add(cell21);

        cell22.setBackground(new java.awt.Color(222, 212, 210));
        add(cell22);

        cell23.setBackground(new java.awt.Color(222, 212, 210));
        add(cell23);

        cell24.setBackground(new java.awt.Color(222, 212, 210));
        add(cell24);

        cell25.setBackground(new java.awt.Color(222, 212, 210));
        add(cell25);

        cell26.setBackground(new java.awt.Color(222, 212, 210));
        add(cell26);

        cell27.setBackground(new java.awt.Color(222, 212, 210));
        add(cell27);

        cell28.setBackground(new java.awt.Color(222, 212, 210));
        add(cell28);

        cell29.setBackground(new java.awt.Color(222, 212, 210));
        add(cell29);

        cell30.setBackground(new java.awt.Color(222, 212, 210));
        add(cell30);

        cell31.setBackground(new java.awt.Color(222, 212, 210));
        add(cell31);

        cell32.setBackground(new java.awt.Color(222, 212, 210));
        add(cell32);

        cell33.setBackground(new java.awt.Color(222, 212, 210));
        add(cell33);

        cell34.setBackground(new java.awt.Color(222, 212, 210));
        add(cell34);

        cell35.setBackground(new java.awt.Color(222, 212, 210));
        add(cell35);

        cell36.setBackground(new java.awt.Color(222, 212, 210));
        add(cell36);

        cell37.setBackground(new java.awt.Color(222, 212, 210));
        add(cell37);

        cell38.setBackground(new java.awt.Color(222, 212, 210));
        add(cell38);

        cell39.setBackground(new java.awt.Color(222, 212, 210));
        add(cell39);

        cell40.setBackground(new java.awt.Color(222, 212, 210));
        add(cell40);

        cell41.setBackground(new java.awt.Color(222, 212, 210));
        add(cell41);

        cell42.setBackground(new java.awt.Color(222, 212, 210));
        add(cell42);

        cell43.setBackground(new java.awt.Color(222, 212, 210));
        add(cell43);

        cell44.setBackground(new java.awt.Color(222, 212, 210));
        add(cell44);

        cell45.setBackground(new java.awt.Color(222, 212, 210));
        add(cell45);

        cell46.setBackground(new java.awt.Color(222, 212, 210));
        add(cell46);

        cell47.setBackground(new java.awt.Color(222, 212, 210));
        add(cell47);

        cell48.setBackground(new java.awt.Color(222, 212, 210));
        add(cell48);

        cell49.setBackground(new java.awt.Color(222, 212, 210));
        add(cell49);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Agenda.Cell cell10;
    private Agenda.Cell cell11;
    private Agenda.Cell cell12;
    private Agenda.Cell cell13;
    private Agenda.Cell cell14;
    private Agenda.Cell cell15;
    private Agenda.Cell cell16;
    private Agenda.Cell cell17;
    private Agenda.Cell cell18;
    private Agenda.Cell cell19;
    private Agenda.Cell cell20;
    private Agenda.Cell cell21;
    private Agenda.Cell cell22;
    private Agenda.Cell cell23;
    private Agenda.Cell cell24;
    private Agenda.Cell cell25;
    private Agenda.Cell cell26;
    private Agenda.Cell cell27;
    private Agenda.Cell cell28;
    private Agenda.Cell cell29;
    private Agenda.Cell cell30;
    private Agenda.Cell cell31;
    private Agenda.Cell cell32;
    private Agenda.Cell cell33;
    private Agenda.Cell cell34;
    private Agenda.Cell cell35;
    private Agenda.Cell cell36;
    private Agenda.Cell cell37;
    private Agenda.Cell cell38;
    private Agenda.Cell cell39;
    private Agenda.Cell cell40;
    private Agenda.Cell cell41;
    private Agenda.Cell cell42;
    private Agenda.Cell cell43;
    private Agenda.Cell cell44;
    private Agenda.Cell cell45;
    private Agenda.Cell cell46;
    private Agenda.Cell cell47;
    private Agenda.Cell cell48;
    private Agenda.Cell cell49;
    private Agenda.Cell cell8;
    private Agenda.Cell cell9;
    private Agenda.Cell fri;
    private Agenda.Cell mon;
    private Agenda.Cell sat;
    private Agenda.Cell sun;
    private Agenda.Cell thu;
    private Agenda.Cell tue;
    private Agenda.Cell wed;
    // End of variables declaration//GEN-END:variables
}
